name: automated tests

on:
  push: null
  pull_request: null
  schedule:
  - cron: 0 0 * * *

_anchors:
  get_version: &get_version
    name: get package version
    run: echo "::set-output name=version::"`jq -r .version package.json`
    id: version
  install_python: &install_python
    name: install python
    uses: actions/setup-python@v2
    with:
      python-version: '3.10'
  install_node: &install_node
    name: install node
    uses: actions/setup-node@v2
    with:
      node-version: 16.x
  cache: &cache
    name: Cache python/node dependencies
    id: cache
    uses: actions/cache@v3
    env:
      cache-name: v3
    with:
      path: |
        ~/.npm
        ~/.nocache/pip
        ${{ env.pythonLocation }}
      key: ${{ runner.os }}-build-${{ env.pythonLocation }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('requirements.txt') }}
  install_python_packages: &install_python_packages
    name: install python packages
    run: |
      pip install packaging
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  install_node_packages: &install_node_packages
    name: install node packages
    run: npm install

env:
  DURATIONS: test/stats/durations.json
  BINS: test/stats/bins.json

jobs:
  jobs:
    outputs:
      bins: ${{ steps.balance.outputs.bins }}
      clients: ${{ steps.balance.outputs.clients }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - *install_python
    - run: pip install munch ortools
    - *get_version
    - name: get previous test durations
      run: curl -L https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/`basename $DURATIONS` --create-dirs -o $DURATIONS
    - name: select test scope
      id: slow
      if: github.ref == 'refs/heads/master'
      run: echo "::set-output name=slow::--slow"
    - name: balance tests
      id: balance
      run: ./util/balance.py --durations $DURATIONS --bins $BINS ${{ steps.slow.outputs.slow }} --beta ${{ (github.event.head_commit.message == steps.version.outputs.version && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'schedule' }}
    - name: store test job split
      uses: actions/upload-artifact@v2
      with:
        name: test-stats
        path: ${{ env.BINS }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - *get_version
    - name: cancel spurious build on tagged version
      uses: andymckay/cancel-action@master
      if: github.event.head_commit.message == steps.version.outputs.version && !startsWith(github.ref, 'refs/tags/')

    - *install_python
    - *install_node
    - *cache
    - *install_python_packages
    - *install_node_packages

    - run: npm run build

    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          xpi/
          gen/

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true
    - run: npm run docs:deploy
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/public

  test:
    needs:
    - build
    - jobs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bin: ${{ fromJSON(needs.jobs.outputs.bins) }}
        client: ${{ fromJSON(needs.jobs.outputs.clients) }}
    steps:
    - uses: actions/checkout@v2
    - name: fetch build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: fetch test stats
      uses: actions/download-artifact@v2
      with:
        name: test-stats
    - run: find . -name bins.json
      
    - *install_python
    - *cache
    - *install_python_packages

    - name: install ${{ matrix.client }}
      run: |
        curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
        sudo apt-get update
        sudo apt-get install ${{ matrix.client }}

    - name: install ${{ matrix.client }} beta
      if: matrix.client != 'jurism'
      run: sudo apt-get install ${{ matrix.client }}-beta

    # fast test
    - if: contains(github.event.commits[0].message, '[fast-test]')
      run: echo "##[set-output name=this;]--test-this"
      id: test

    # needs logs/logs to have them show up as logs in the artifact... no idea why
    - name: Run tests
      # continue-on-error: ${{ matrix.client == 'jurism' }}
      run: xvfb-run --auto-servernum ./test/behave --client ${{ matrix.client }} --logs logs/logs --format ci --bin ${{ matrix.bin }} --bins $BINS ${{ steps.test.outputs.this }}
      env:
        PYTHONUNBUFFERED: true

    - uses: actions/upload-artifact@v2
      if: ${{ failure() || cancelled() }}
      with:
        name: debug log ${{ matrix.client }} ${{ matrix.bin }}
        path: ~/.BBTZ5TEST.log

    - name: store test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          logs/

#    - name: Setup tmate session
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true

  release:
    if: github.event_name != 'schedule'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: fetch build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts

    - *install_python
    - *install_node
    - *cache
    - *install_python_packages
    - *install_node_packages

    - run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  durations:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: fetch build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: rebalance tests
      run: |
        ./util/merge-logs.py -o $DURATIONS logs/behave-zotero-release-*-master.json
        ./util/merge-logs.py -o test/stats/loaded.json logs/loaded-zotero-release-*-master.json
    - name: Store build stats
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: test/stats/*.json
        tag: builds
        overwrite: true
        file_glob: true
