name: 'Manage issues and nag about support logs'

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created, edited, closed]

jobs:
  nag:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@main
        with:
          token: ${{ github.token }}
          label.exempt: question
          log-id.label: needs-support-log
          log-id.regex: "[A-Z0-9]{8}(-refs)?-(apse|euc)"
          log-id.message: |
            It looks like you did not upload an support log. The support log is important; it gives @retorquere your current BBT settings and a copy of the problematic reference as a test case so he can best replicate your problem. Without it, @retorquere is effectively blind. Support logs are useful for both analysis and for enhancement requests; in the case of export enhancements, @retorquere needs the copy of the references you have in mind.

            If you did try to submit a support log, but the ID looked like `D<number>`, that is a Zotero debug report, which @retorquere cannot access. Please re-submit a BBT debug log by one of the methods below. BBT support log IDs end in `-apse` or `-euc`. Support logs that include sample references will end in `-refs-apse` or `-refs-euc`; these are the type @retorquere needs for diagnos.

            **This request is much more likely than not to apply to you, too, _even if you think it unlikely_**, and even if it does not, there's no harm in sending a debug log that turns out to be unnecessary. @retorquere will usually just end up saying "please send a debug log first". Let's just skip over the unnecesary delay this entails. Sending a debug log is very easy, depending on your situation, follow one of these procedures:

            1. If your issue relates to how BBT behaves around a **specific reference(s)**, such as citekey generation or export, select at least one of the problematic reference(s), right-click it, and submit an BBT support log from that popup menu. If the problem is with export, please do include a sample of what you see exported, and what you expected to see exported for these references, either by pasting it in a comment here (if it is small) or attaching it as a `.txt` file (if it's large). These logs will have an ID that ends in `-refs-apse` or `-refs-euc`.

            2. If the issue **does not relate to references** and is of a more general nature, generate an support log by restarting Zotero with debugging enabled (`Help` -> `Debug Output Logging` -> `Restart with logging enabled`), reproducing your problem, and selecting `Send Better BibTeX debug report...` from the help menu.

            Once done, you will see a support log ID in red. Please post that support log id in an issue comment here.

            Thank you!
          log-id.prompt: "Support log ID (with `-apse` or `-euc`):"
          no-close.message: Thanks for the feedback; there's no way you could have known, but @retorquere prefers to keep bugreports/enhancements open as a reminder to merge the changes into a new release.
